#!/usr/bin/env php

<?php

require_once 'CreateInstance.php';

// название файла с командами в виде строки
$commands = 'commands.php';

$app = new CreateInstance($commands);
$app->run($argv);

/*
echo $argv[0];
echo $argv[1]; // параметр1
echo $argv[2]; // параметр2
*/
// и тд
// $argv массив параметров, полученных из консоли