#!/usr/bin/env php

<?php

require_once 'CreateInstance.php';
/*
echo $argv[0];
echo $argv[1]; // параметр1
echo $argv[2]; // параметр2
*/
// и тд
// $argv массив параметров, полученных из консоли

$app = new CreateInstance();
$app->run();